In [44]:
import numpy as np

In [100]:
#def bisection(a,b):
    
def charac_poly(a,b):

    f = np.zeros(len(a))


    


    for i in range(len(a)):
        

        if i == 0:

            f[i] = 1 

        else:

            f[i] = (a[i - 1]) * f[i - 1] - b[i - 2]**2 * f[i - 2]
            
    charac_poly = f[len(f) - 1]        

    return charac_poly 
    
    
def bifunction(a,b,wert1,wert2,max_count, tolerance):
    
    count = 0
    
    while np.abs(wert2 - wert1) > tolerance and count < max_count:
        
        
            
        if charac_poly(a - wert2,b) * charac_poly((wert1 + wert2) / 2, b) > 0:

            wert1 = (wert1 + wert2) / 2

        if charac_poly(a - wert1,b) * charac_poly((wert1 + wer2) / 2,b) > 0:

            wert2 = (wert1 + wert2) / 2

        count += 1 
        
        return wert1
    
    
        
            
            
            
    

    



            

In [97]:

print(charac_poly(np.full(3,2),np.full(2,1)))


durchgang= 0
durchgang= 1
2.0
durchgang= 2
3.0
charac_poly 3.0
None


In [65]:
for i in range(4):
    print(i)
    
print(len([1,2,3,4]))

0
1
2
3
4


In [75]:
a = np.zeros((4,4))
print(a)
b = np.shape(a)
print(b)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
(4, 4)
