In [1]:
import numpy as np
from numpy import linalg as LA

In [2]:
#Function stopping returning False as soon as all values of A are lower then max, returns True as soon as there is only one number bigger than max

def condition(A,max):

    for i in range(len(A)):
        for j in range(len(A)):


            if i !=j:
                if np.abs(A[i,j]) > max:
                    return True

    return False

In [3]:
def rotation(A,l,k,v): 
# A er matricen der skal diagonaliseres
# l, k er positionerne for rotationsledende og positionerne i A der bliver minimeret
# v er en mastrix bestående af basisvektorene


    B = np.copy(A)

    w = np.copy(v)

    tau = (A[l,l] - A[k,k]) / (2 * A[k,l])
#tau er defineret sådan så vi får en andengradsligning

    tplus  = -tau + np.sqrt(1 + tau**2)
    tminus = -tau - np.sqrt(1 + tau**2)
#Udfra betingelsen at b_kl = 0, får vi en andengradsligning med disse løsninger for t        

    if abs(tplus) < abs(tminus):
        t = tplus
    else:
        t = tminus
#Vi skal åbenbart altid vælge den mindre t?

    c = 1 / (np.sqrt(1 + t**2))

    s = t * c

    for j in range(len(v)):
        w[j,k] =   c * v[j,k] - s * v[j,l]
        w[j,l] =   s * v[j,k] + c * v[j,l]
#Vi fandt ud af ved testing at, hvis vi bruger rotatione matricen, sker der kun noget med k'te og l'te række i vær enkel søjle
#Da der var fejl i rækkefølje af vœrdierne af eigenvektorene, har vi nu byttet om på søjler og rækker (j,k/l)


    B[k,k] = A[k,k] * c**2 - 2 * A[k,l] * c * s + A[l,l] * s**2
    B[l,l] = A[l,l] * c**2 + 2 * A[k,l] * c * s + A[k,k] * s**2
    B[k,l] = B[l,k] = 0
# Her sker selve rotationen

    for i in range(len(A)):


        if i != k and i != l:
            #B[i,i] = A[i,i]
            B[i,k] = B[k,i] = A[i,k] * c - A[i,l] * s
            B[i,l] = B[l,i] = A[i,l] * c + A[i,k] * s
#Alle andre led i k,l -række/søjle ændrer også værdi


    return B,w

In [4]:
#define function that always finds positions of highest non-diagonal matrix entrances:

def highestkl(A):
    
    l = k = 0

    highestmatrixentry = 0  


    for i in range(len(A)):
        for j in range(len(A)):

            if i != j: 

                if np.abs(A[i,j]) > highestmatrixentry:

                    highestmatrixentry = np.abs(A[i,j])
                    l, k = i, j
                        
        return l,k



In [5]:
 
def code(n):  
    
#Definere A udfra vores andengradslignings problem, definere v som matrix med enhedsvektorer, definere max:    
    A =          2*np.eye(n,n) + -1 * np.eye(n,n,k=-1) + -1 * np.eye(n,n,k=1)
    Aunchanged = 2*np.eye(n,n) + -1 * np.eye(n,n,k=-1) + -1 * np.eye(n,n,k=1)
    v = np.eye(n,n)
    max = 10**(-10)   
    count = 0
    max_count = 100
    
    
    
    
    
    while condition(A,max) and count < max_count:    

        
        highestmatrixentry = 0  


        for i in range(len(A)):
            for j in range(len(A)):

                if i != j: 

                    if np.abs(A[i,j]) > highestmatrixentry:

                        highestmatrixentry = np.abs(A[i,j])
                        l, k = i, j

        
#Finder positionen af den højeste matrice indgang, med et loop som går igennem alle indgangene og opdaterer den højeste indgangs vœrdi/position

        
        A,v = rotation(A,l,k,v)
        #print("===============")
        #print(A)


        count += 1


        
        
########################### Solutions ######################################################        
        
    print('diagonalized matrix:')
    print(A)
    print('Matrix of eigvectors:')
    print(v)
    print('number of rotations =', count)
    print()
    
    return A,v

     
A,v = code(4)








diagonalized matrix:
[[2.61803399 0.         0.         0.        ]
 [0.         1.38196601 0.         0.        ]
 [0.         0.         3.61803399 0.        ]
 [0.         0.         0.         0.38196601]]
Matrix of eigvectors:
[[ 0.60150096  0.60150096  0.37174803  0.37174803]
 [-0.37174803  0.37174803 -0.60150096  0.60150096]
 [-0.37174803 -0.37174803  0.60150096  0.60150096]
 [ 0.60150096 -0.60150096 -0.37174803  0.37174803]]
number of rotations = 6



In [6]:
########################### Tests #########################################  

print('Test: orthogonality of Eigenvectors:')


def orthogonalitytest(v):
    
    T = np.dot(np.transpose(v),v)
    print('Inner product', np.dot(np.transpose(v),v))
    
    for i in range(len(v)):
        for j in range(len(v)):
            if i == j: 
    
                if T[i,j] < 0.999 or T[i,j] > 1.001:

                    return False

                else:

                    pass
            if i!= j: 
                print(T[i,j])
                if T[i,j] < -0.011 or T[i,j] > 0.001:

                    return False
                else:
                    pass

    return True

orthogonalitytest(v)

Test: orthogonality of Eigenvectors:
Inner product [[1.00000000e+00 0.00000000e+00 2.99060035e-18 0.00000000e+00]
 [0.00000000e+00 1.00000000e+00 0.00000000e+00 2.99060035e-18]
 [2.99060035e-18 0.00000000e+00 1.00000000e+00 0.00000000e+00]
 [0.00000000e+00 2.99060035e-18 0.00000000e+00 1.00000000e+00]]
0.0
2.990600352469157e-18
0.0
0.0
0.0
2.990600352469157e-18
2.990600352469157e-18
0.0
0.0
0.0
2.990600352469157e-18
0.0


True